
on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        working-directory: ./myapp
        run: npm install
#      - name: npm test
#       run: npm test
#      - name: npm lint
#        run: npm lint
      - name: docker build
        working-directory: ./myapp
        run: docker build -t raviverma/repo1/github-cicd-eks .
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin docker.io
      - name: dockerhub push
        working-directory: ./myapp
        run : docker push raviverma/repo1/github-cicd-eks
#      - name: Push to Docker Hub
#        working-directory: ./myapp
#        run: docker build -t rv-github-cicd-eks . , docker push raviverma/repo1:rv-github-cicd-eks
