
on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        run: npm install
#      - name: npm test
#       run: npm test
#      - name: npm lint
#        run: npm lint
#      - name: docker build
#        run: docker build -t raviverma/repo1/github-cicd-eks .
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin docker.io
      - name: build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: raviverma/repo1:latest
